CREATE DATABASE IF NOT EXISTS bookstore;

CREATE USER IF NOT EXISTS 'bookstore_user'@'%' IDENTIFIED BY 'bookstore_pass';

GRANT SELECT, RELOAD, SHOW DATABASES, LOCK TABLES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'bookstore_user'@'%';

GRANT ALL PRIVILEGES ON bookstore.* TO 'bookstore_user'@'%';

FLUSH PRIVILEGES;
